# Generated by Django 3.2.3 on 2021-06-01 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Unsent', 'Unsent'), ('Cancelled', 'Cancelled'), ('Sent', 'Sent')], max_length=50)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
