# Generated by Django 3.2.3 on 2021-06-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='image',
        ),
    ]
