# Generated by Django 3.2.2 on 2021-05-07 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_defaultpassword', models.BooleanField(default=False)),
                ('profile_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.JSONField(blank=True, null=True)),
                ('enable_phone_notification', models.BooleanField(blank=True, null=True)),
                ('enable_email_notification', models.BooleanField(blank=True, null=True)),
                ('enable_system_notification', models.BooleanField(blank=True, null=True)),
                ('primary_role', models.CharField(blank=True, max_length=255, null=True)),
                ('identification_type', models.CharField(blank=True, max_length=255, null=True)),
                ('date_registered', models.DateTimeField(auto_now=True)),
                ('account_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('IN_ACTIVE', 'IN_ACTIVE')], default='ACTIVE', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'systemusers',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=30)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_department', to='authentication.agency')),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('REVOKED', 'REVOKED')], default='ACTIVE', max_length=255)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('REVOKED', 'REVOKED')], default='ACTIVE', max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('department_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_section', to='authentication.department')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('DEACTIVATED', 'DEACTIVATED')], max_length=100)),
                ('date_created', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user_mapping', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.usercategory')),
                ('user_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.department')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategoryType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('serializer', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_category_type', to='authentication.usercategory')),
            ],
        ),
        migrations.CreateModel(
            name='TeamCategoryType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_category_type', to='authentication.teamcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAccountUsers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('is_team_admin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('REVOKED', 'REVOKED')], max_length=100)),
                ('team_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_account', to='authentication.teamaccount')),
                ('team_account_user_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.teamcategorytype')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='teamaccount',
            name='team_account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.teamcategory'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('employeenum', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phonenum', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('identification_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_phoneverified', models.BooleanField(default=False)),
                ('is_emailverified', models.BooleanField(default=False)),
                ('is_passwordverified', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now=True)),
                ('user_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_department', to='authentication.department')),
                ('user_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_designation', to='authentication.designation')),
                ('user_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_user_section', to='authentication.section')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='PublicUserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phonenum', models.CharField(blank=True, max_length=1000, null=True)),
                ('fullname', models.CharField(blank=True, max_length=1000, null=True)),
                ('firstname', models.CharField(blank=True, max_length=1000, null=True)),
                ('middlename', models.CharField(blank=True, max_length=1000, null=True)),
                ('lastname', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, max_length=1000, null=True)),
                ('mothermaiden', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_phoneverified', models.BooleanField(default=False)),
                ('is_emailverified', models.BooleanField(default=False)),
                ('is_passwordverified', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now=True)),
                ('userid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenum', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('date_registered', models.DateTimeField(auto_now=True)),
                ('teamid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_team', to='authentication.teamaccount')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='CodeVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phonenum', models.IntegerField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('generationtime', models.DateTimeField()),
                ('exptime', models.DateTimeField()),
                ('status', models.CharField(choices=[('REVOKED', 'REVOKED'), ('PENDING', 'PENDING')], max_length=10)),
                ('vrftype', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'EMAIL')], max_length=50)),
                ('module', models.CharField(choices=[('LOGIN', 'LOGIN'), ('REGISTRATION', 'REGISTRATION')], max_length=50)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountVerificationLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_level', models.CharField(blank=True, choices=[('BUSINESS_REGISTRATION_SERVICE', 'BUSINESS_REGISTRATION_SERVICE'), ('PHYSICAL_VERIFICATION', 'PHYSICAL_VERIFICATION'), ('NRB_VERIFICATION', 'NRB_VERIFICATION')], max_length=1000, null=True)),
                ('verification_step', models.CharField(blank=True, max_length=255, null=True)),
                ('date_verified', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_verification_level', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSecurityQuestions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer_status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('REVOKED', 'REVOKED'), ('RESET', 'RESET')], max_length=1000, null=True)),
                ('security_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_user_security_questions', to='authentication.securityquestions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_user_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.usercategorytype'),
        ),
    ]
