# Generated by Django 3.2 on 2021-05-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identification_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='signature',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='mwangyjose@gmail.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='enable_system_notification',
            field=models.BooleanField(default=True),
        ),
    ]
