# Generated by Django 3.2 on 2021-05-15 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210515_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeverification',
            name='email',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.AlterField(
            model_name='accountverificationlevel',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_verification_level', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_user', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='teamaccountusers',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_user_account', to='authentication.user'),
        ),
    ]
