# Generated by Django 3.2.3 on 2021-06-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_username_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeverification',
            name='phonenum',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='phonenum',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='phonenum',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phonenum',
        ),
    ]
