# Generated by Django 3.2.3 on 2021-06-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210601_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicuserprofile',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='middlename',
        ),
    ]
