# Generated by Django 3.2.3 on 2021-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210604_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicuserprofile',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
