# Generated by Django 3.2.3 on 2021-06-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_publicuserprofile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuserprofile',
            name='profile_photo',
        ),
    ]
